#This Job computes the value of Pi to 2,000 places and then prints the result.
apiVersion: batch/v1
kind: Job #make deployment kind job 
metadata:
  # Unique key of the Job instance
  name: example-job
spec:
  template:
    metadata:
      name: example-job
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl"]
        args: ["-Mbignum=bpi", "-wle", "print bpi(2000)"]
      # Do not restart containers after they exit instead if container failed for any reason without task being executed launch another pod
      restartPolicy: Never
